### ISSUE TITLE
TypeError: Cannot read property 'businessmessages_v1' of undefined

### ISSUE THREAD

**Issue by Mistic92** [google-business-communications/nodejs-businessmessages#1]
When I'm trying to use example code with typescript I'm getting undefined error. 

```ts
// Get the BusinessMessages client library
import businessmessages from "businessmessages";

// Initialize the Business Messages client library
const bmApi = new businessmessages.businessmessages_v1.Businessmessages({});
```

```

/root/projects/business-messaging/src/businessmessaging/bmService.ts:9
const bmApi = new businessmessages.businessmessages_v1.Businessmessages({});
                                   ^
TypeError: Cannot read property 'businessmessages_v1' of undefined
    at Object.<anonymous> (/root/projects/business-messaging/src/businessmessaging/bmService.ts:9:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/projects/business-messaging/src/app.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    ```

I'm using vertion 1.0.3

**Comment by Mistic92** [comment]
When I used require it worked but I'm missing types etc
```
const businessmessages = require('businessmessages');
```

**Comment by thefalc** [comment]
Hi Mistic92,

Sorry for the slow response on this. What do you mean by missing types? Can you share an example?

Sean

**Comment by OpenDog** [comment]
He meant the TypeScript definitions.
